import Features from "./Home/Features";
import Hero from "./Home/Hero";
import Packages from "./Hall/Packages";
import Subcribe from "./Home/Subcribe";
import Testimonial from "./Home/Testimonial";
import Choose from "../components/Home/Choose";
import Occation from "./Hall/Occation";
import Messages from "./Hall/Messages";
import Inspired from "./Hall/Inspired";
import Platform from "./Hall/Platform";
export { Features, Hero, Packages, Subcribe, Testimonial, Choose };
export { Occation, Messages, Inspired, Platform };
